version = 0.1

[default.deploy.parameters]
stack_name = "aihelper"
resolve_s3 = true
s3_prefix = "aihelper"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\""
image_repositories = []
