AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI Assistant - Working Telegram Bot and Calendar Integration

# Global configuration for all functions
Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.13
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: aihelper
        LOG_LEVEL: INFO
        ENVIRONMENT: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # DynamoDB Tables - Only what we need
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'aihelper-users-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: N
        - AttributeName: sort_key
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  CalendarEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'aihelper-calendar-events-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: N
        - AttributeName: start_time
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
        - AttributeName: start_time
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserTimeIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: start_time
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # API Gateway for webhook
  TelegramWebhookApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  # Lambda Functions - Only working ones
  TelegramBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'aihelper-telegram-bot-${Environment}'
      CodeUri: lambdas/telegram_bot
      Handler: handler.lambda_handler
      Description: Handles incoming Telegram messages via webhook
      Environment:
        Variables:
          USERS_TABLE: !Sub 'aihelper-users-${Environment}'
          BOT_TOKEN_SECRET: 'telegram-bot-token-dev'
          ENVIRONMENT: !Ref Environment
      Events:
        WebhookApi:
          Type: Api
          Properties:
            RestApiId: !Ref TelegramWebhookApi
            Path: /webhook
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: 'arn:aws:secretsmanager:*:*:secret:telegram-bot-token-dev*'

  CalendarFetcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'aihelper-calendar-fetcher-${Environment}'
      CodeUri: lambdas/calendar_fetcher
      Handler: handler.lambda_handler
      Description: Fetches calendar events from Google Calendar
      Environment:
        Variables:
          CALENDAR_EVENTS_TABLE: !Sub 'aihelper-calendar-events-${Environment}'
          GOOGLE_CREDENTIALS_SECRET: 'google-calendar-credentials-dev'
          ENVIRONMENT: !Ref Environment
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CalendarEventsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: 'arn:aws:secretsmanager:*:*:secret:google-calendar-credentials-dev*'

  # EventBridge Rules - Only for working functions
  CalendarSyncRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub 'aihelper-calendar-sync-${Environment}'
      Description: Syncs calendar events every hour
      ScheduleExpression: cron(0 */1 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt CalendarFetcherFunction.Arn
          Id: CalendarSyncTarget

  # Lambda Permission for EventBridge
  CalendarFetcherPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CalendarFetcherFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CalendarSyncRule.Arn

Outputs:
  TelegramBotApiUrl:
    Description: API Gateway URL for Telegram Bot webhook
    Value: !Sub 'https://${TelegramWebhookApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/webhook'
    Export:
      Name: !Sub '${AWS::StackName}-telegram-bot-api-url'

  CalendarFetcherFunctionArn:
    Description: Calendar Fetcher Lambda function ARN
    Value: !GetAtt CalendarFetcherFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-calendar-fetcher-arn'

  DynamoDBTables:
    Description: DynamoDB table names
    Value: !Sub |
      Users: ${UsersTable}
      Calendar Events: ${CalendarEventsTable}
    Export:
      Name: !Sub '${AWS::StackName}-dynamodb-tables'
